# -*- coding: utf-8 -*-
{
    'name': 'Hospedaje',
    'version': '',
    'description': """ Módulo para la gestión de hospedajes """,
    'summary': """ Módulo que permite la gestión de hospedajes """,
    'author': 'Yankiel Yong',
    'website': '',
    'category': 'Services/Hospedaje',
    'depends': ['base', 'mail'],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/habitacion_views.xml",
        "views/res_partner_views.xml",
        "views/reservacion_views.xml",
        "views/entrada_views.xml",
        "views/salida_views.xml",
        "views/tipo_habitacion_views.xml",
        "views/hospedaje_menu.xml",
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
